name: ML CI/CD Pipeline

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Dependencies
        run: pip install -r requirements.txt
    

  build_and_deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: |
          docker build -t ai_demo_model_image:latest .

      - name: Verify Docker Hub Credentials
        run: |
          echo "Docker Hub Username: $DOCKER_HUB_USERNAME"
          echo "Docker Hub Access Token Length: ${#DOCKER_HUB_ACCESS_TOKEN}"
    # Do NOT print the access token directly to avoid leaking it

      - name: Log in to Docker Hub
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        run: |
          echo "$DOCKER_HUB_ACCESS_TOKEN" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin

      - name: Push Docker Image to Docker Hub
        run: |
          docker tag ai_demo_model_image:latest bodduprasad/ai_demo_model_image:latest
          docker push bodduprasad/ai_demo_model_image:latest

      - name: Run Model Training in Docker
        run: |
          docker run --rm ai_demo_model_image:latest

      - name: Deploy Model
        if: success() && steps.train.outputs.metrics.accuracy > 0.95
        run: |
          # Deployment code here, such as uploading to a model registry
          mlflow models serve -m /path/to/model -h 0.0.0.0 -p 5000
